<a href="https://colab.research.google.com/github/armandoordonez/eda_couse/blob/main/3_4_practica_selecci_n_de_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Selección de variables

## 0. Importar las librerias

In [ ]:
#Importamos las librerias que usaremos en este practica

import pandas as pd
import numpy as np
import seaborn as sns

sns.set_theme(style="whitegrid")

## 1. Cargar el data set

### 1.1 Usando la libreria de drive

In [ ]:
#Importamos la libreria de drive

from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [ ]:
#Creamos nuestra variable df, que sera nuestro dataframe
#Usamos pd (la libreria de pandas, que fue definida en la celda donde importamos las librerias) para leer el dataset y asignarlo a df
df = pd.read_csv('https://raw.githubusercontent.com/armandoordonez/eda_couse/refs/heads/main/data/diabetes.csv',    #Ruta completa a la ubicación del archivo de interés.
                 na_values='?')              #Como el archivo contiene algunos caracteres ?, con este comando pandas los interpreta como nan (not a number).

### 1.2 Cargando el archivo a google colab

## 2. Observaciones basicas del dataset

### Tamaño del dataset

In [ ]:
df.shape

(768, 9)

### información general

Podemos observar el nombre de las columnas, si tienen nulos y cual es su tipo de dato

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

### Vista preliminar

Observamos los primeros y ultimos 5 datos del data set

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## 3.1 Sin selección de variables

*Vamos* a probar nuestro modelo usando todas las variables del data set

In [ ]:
#Escojamos nuestras variables predictoras
predictores = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
#Escojamos que es lo que queremos encontrar
objetivo= 'Outcome'

#Recordemos que en nuestra variable Y va lo que queremos encontrar/predecir.
#Mientras en la vairable X van las variables que usaremos para encontrar a Y
y= df[objetivo].values
X= df[predictores].values

In [ ]:
from sklearn.model_selection import train_test_split
# Crear conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(614, 8)
(154, 8)
(614,)
(154,)

In [ ]:
# Se importa el modelo
from sklearn.linear_model import LogisticRegression

#Se crea el modelo
log_reg = LogisticRegression(solver='lbfgs',max_iter=1000)
# https://es.wikipedia.org/wiki/L-BFGS
#se entrena el modelo
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
log_reg.score(X_test, y_test)

0.7467532467532467

## 3.2 Con selección de variables

Para saber que variables vamos a seleccionar tenemos la correlación.

La correlación es una representación de la relación entre dos variables, entre más cercana a 1 mejor.

En este caso, observaremos la correlación entre todas nuestras variables en X con nuestra variable Y.

In [ ]:
df.corr()['Outcome'].nlargest(10)

Outcome                     1.000000
Glucose                     0.466581
BMI                         0.292695
Age                         0.238356
Pregnancies                 0.221898
DiabetesPedigreeFunction    0.173844
Insulin                     0.130548
SkinThickness               0.074752
BloodPressure               0.065068
Name: Outcome, dtype: float64

Primero, el primer dato lo podemos ignorar, dado que la correlación entre nuestra variable objetivo y ella misma siempre sera de 1.

Sin embargo, ahora podemos observar cuales serian los mejores predictores. En este caso, usaremos los primeros 4.

In [ ]:
#Escojamos nuestras variables predictoras
predictores = ['Pregnancies','Glucose','BMI','Age']
#Escojamos que es lo que queremos encontrar
objetivo= 'Outcome'

#Recordemos que en nuestra variable Y va lo que queremos encontrar/predecir.
#Mientras en la vairable X van las variables que usaremos para encontrar a Y
y= df[objetivo].values
X= df[predictores].values

In [ ]:
# Crear conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(614, 4)
(154, 4)
(614,)
(154,)

In [ ]:
#Se crea el modelo
log_reg = LogisticRegression(solver='lbfgs',max_iter=100)
#se entrena el modelo
log_reg.fit(X_train, y_train)

LogisticRegression()

In [ ]:
log_reg.score(X_test, y_test)

0.7532467532467533

Podemos ver que usando solo 4 variables obtuvimos un mejor resultado. Este efecto se puede ver mejor cuando tengamos datasets con muchas más variables.